spring.application.name=student_placment_management_system
spring.datasource.url=jdbc:mysql://localhost:3306/placement_db
spring.datasource.username=root
spring.datasource.password=sonali2006
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true